version: "3.7"
services:
  php:
    build: .
    image: registry.docker.cyclonis.ie/php-7.1
    container_name: php
#    ports:
#      - target: 9000
 #       published: 9000
 #       protocol: tcp
 #       mode: host
    volumes:
      - "/vagrant/test/:/scripts"
    networks:
      localnet:
        aliases: 
          - php.internal.net

  nginx:
    image: registry.docker.cyclonis.ie/nginx
    container_name: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - "/vagrant/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      localnet:
        aliases: 
          - nginx.internal.net

networks:
  localnet:
    driver: bridge